//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyHousingSolutions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public int BuyerId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailId { get; set; }
        public string Adress { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual State State { get; set; }
    }
}
